apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-first-app
  template:
    metadata:
      labels:
        app: my-first-app
    spec:
      containers:
      - name: my-first-app-container
        image: my-first-jenkins-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80
